// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.4.2
//   protoc               v3.19.1
// source: messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import { type CallContext, type CallOptions } from 'nice-grpc-common';
import {
  AddPeerRequestMessage,
  AddPeerResponseMessage,
  BanRequestMessage,
  BanResponseMessage,
  BlockAddedNotificationMessage,
  EstimateNetworkHashesPerSecondRequestMessage,
  EstimateNetworkHashesPerSecondResponseMessage,
  FinalityConflictNotificationMessage,
  FinalityConflictResolvedNotificationMessage,
  GetBalanceByAddressRequestMessage,
  GetBalanceByAddressResponseMessage,
  GetBalancesByAddressesRequestMessage,
  GetBalancesByAddressesResponseMessage,
  GetBlockCountRequestMessage,
  GetBlockCountResponseMessage,
  GetBlockDagInfoRequestMessage,
  GetBlockDagInfoResponseMessage,
  GetBlockRequestMessage,
  GetBlockResponseMessage,
  GetBlocksRequestMessage,
  GetBlocksResponseMessage,
  GetBlockTemplateRequestMessage,
  GetBlockTemplateResponseMessage,
  GetCoinSupplyRequestMessage,
  GetCoinSupplyResponseMessage,
  GetConnectedPeerInfoRequestMessage,
  GetConnectedPeerInfoResponseMessage,
  GetConnectionsRequestMessage,
  GetConnectionsResponseMessage,
  GetCurrentBlockColorRequestMessage,
  GetCurrentBlockColorResponseMessage,
  GetCurrentNetworkRequestMessage,
  GetCurrentNetworkResponseMessage,
  GetDaaScoreTimestampEstimateRequestMessage,
  GetDaaScoreTimestampEstimateResponseMessage,
  GetFeeEstimateExperimentalRequestMessage,
  GetFeeEstimateExperimentalResponseMessage,
  GetFeeEstimateRequestMessage,
  GetFeeEstimateResponseMessage,
  GetHeadersRequestMessage,
  GetHeadersResponseMessage,
  GetInfoRequestMessage,
  GetInfoResponseMessage,
  GetMempoolEntriesByAddressesRequestMessage,
  GetMempoolEntriesByAddressesResponseMessage,
  GetMempoolEntriesRequestMessage,
  GetMempoolEntriesResponseMessage,
  GetMempoolEntryRequestMessage,
  GetMempoolEntryResponseMessage,
  GetMetricsRequestMessage,
  GetMetricsResponseMessage,
  GetPeerAddressesRequestMessage,
  GetPeerAddressesResponseMessage,
  GetServerInfoRequestMessage,
  GetServerInfoResponseMessage,
  GetSinkBlueScoreRequestMessage,
  GetSinkBlueScoreResponseMessage,
  GetSinkRequestMessage,
  GetSinkResponseMessage,
  GetSubnetworkRequestMessage,
  GetSubnetworkResponseMessage,
  GetSyncStatusRequestMessage,
  GetSyncStatusResponseMessage,
  GetSystemInfoRequestMessage,
  GetSystemInfoResponseMessage,
  GetUtxosByAddressesRequestMessage,
  GetUtxosByAddressesResponseMessage,
  GetVirtualChainFromBlockRequestMessage,
  GetVirtualChainFromBlockResponseMessage,
  NewBlockTemplateNotificationMessage,
  NotifyBlockAddedRequestMessage,
  NotifyBlockAddedResponseMessage,
  NotifyFinalityConflictRequestMessage,
  NotifyFinalityConflictResponseMessage,
  NotifyNewBlockTemplateRequestMessage,
  NotifyNewBlockTemplateResponseMessage,
  NotifyPruningPointUtxoSetOverrideRequestMessage,
  NotifyPruningPointUtxoSetOverrideResponseMessage,
  NotifySinkBlueScoreChangedRequestMessage,
  NotifySinkBlueScoreChangedResponseMessage,
  NotifyUtxosChangedRequestMessage,
  NotifyUtxosChangedResponseMessage,
  NotifyVirtualChainChangedRequestMessage,
  NotifyVirtualChainChangedResponseMessage,
  NotifyVirtualDaaScoreChangedRequestMessage,
  NotifyVirtualDaaScoreChangedResponseMessage,
  PingRequestMessage,
  PingResponseMessage,
  PruningPointUtxoSetOverrideNotificationMessage,
  ResolveFinalityConflictRequestMessage,
  ResolveFinalityConflictResponseMessage,
  ShutdownRequestMessage,
  ShutdownResponseMessage,
  SinkBlueScoreChangedNotificationMessage,
  StopNotifyingPruningPointUtxoSetOverrideRequestMessage,
  StopNotifyingPruningPointUtxoSetOverrideResponseMessage,
  StopNotifyingUtxosChangedRequestMessage,
  StopNotifyingUtxosChangedResponseMessage,
  SubmitBlockRequestMessage,
  SubmitBlockResponseMessage,
  SubmitTransactionReplacementRequestMessage,
  SubmitTransactionReplacementResponseMessage,
  SubmitTransactionRequestMessage,
  SubmitTransactionResponseMessage,
  UnbanRequestMessage,
  UnbanResponseMessage,
  UtxosChangedNotificationMessage,
  VirtualChainChangedNotificationMessage,
  VirtualDaaScoreChangedNotificationMessage
} from './rpc';

export const protobufPackage = 'protowire';

export interface KaspadRequest {
  id: number;
  getCurrentNetworkRequest?: GetCurrentNetworkRequestMessage | undefined;
  submitBlockRequest?: SubmitBlockRequestMessage | undefined;
  getBlockTemplateRequest?: GetBlockTemplateRequestMessage | undefined;
  notifyBlockAddedRequest?: NotifyBlockAddedRequestMessage | undefined;
  /** BlockAddedNotificationMessage blockAddedNotification = 1009; */
  getPeerAddressesRequest?: GetPeerAddressesRequestMessage | undefined;
  GetSinkRequest?: GetSinkRequestMessage | undefined;
  getMempoolEntryRequest?: GetMempoolEntryRequestMessage | undefined;
  getConnectedPeerInfoRequest?: GetConnectedPeerInfoRequestMessage | undefined;
  addPeerRequest?: AddPeerRequestMessage | undefined;
  submitTransactionRequest?: SubmitTransactionRequestMessage | undefined;
  notifyVirtualChainChangedRequest?: NotifyVirtualChainChangedRequestMessage | undefined;
  /** VirtualChainChangedNotificationMessage virtualChainChangedNotification = 1024; */
  getBlockRequest?: GetBlockRequestMessage | undefined;
  getSubnetworkRequest?: GetSubnetworkRequestMessage | undefined;
  getVirtualChainFromBlockRequest?: GetVirtualChainFromBlockRequestMessage | undefined;
  getBlocksRequest?: GetBlocksRequestMessage | undefined;
  getBlockCountRequest?: GetBlockCountRequestMessage | undefined;
  getBlockDagInfoRequest?: GetBlockDagInfoRequestMessage | undefined;
  resolveFinalityConflictRequest?: ResolveFinalityConflictRequestMessage | undefined;
  notifyFinalityConflictRequest?: NotifyFinalityConflictRequestMessage | undefined;
  /**
   * FinalityConflictNotificationMessage finalityConflictNotification = 1041;
   * FinalityConflictResolvedNotificationMessage finalityConflictResolvedNotification = 1042;
   */
  getMempoolEntriesRequest?: GetMempoolEntriesRequestMessage | undefined;
  shutdownRequest?: ShutdownRequestMessage | undefined;
  getHeadersRequest?: GetHeadersRequestMessage | undefined;
  notifyUtxosChangedRequest?: NotifyUtxosChangedRequestMessage | undefined;
  /** UtxosChangedNotificationMessage utxosChangedNotification = 1051; */
  getUtxosByAddressesRequest?: GetUtxosByAddressesRequestMessage | undefined;
  getSinkBlueScoreRequest?: GetSinkBlueScoreRequestMessage | undefined;
  notifySinkBlueScoreChangedRequest?: NotifySinkBlueScoreChangedRequestMessage | undefined;
  /** SinkBlueScoreChangedNotificationMessage sinkBlueScoreChangedNotification = 1058; */
  banRequest?: BanRequestMessage | undefined;
  unbanRequest?: UnbanRequestMessage | undefined;
  getInfoRequest?: GetInfoRequestMessage | undefined;
  stopNotifyingUtxosChangedRequest?: StopNotifyingUtxosChangedRequestMessage | undefined;
  notifyPruningPointUtxoSetOverrideRequest?: NotifyPruningPointUtxoSetOverrideRequestMessage | undefined;
  /** PruningPointUtxoSetOverrideNotificationMessage pruningPointUtxoSetOverrideNotification = 1069; */
  stopNotifyingPruningPointUtxoSetOverrideRequest?: StopNotifyingPruningPointUtxoSetOverrideRequestMessage | undefined;
  estimateNetworkHashesPerSecondRequest?: EstimateNetworkHashesPerSecondRequestMessage | undefined;
  notifyVirtualDaaScoreChangedRequest?: NotifyVirtualDaaScoreChangedRequestMessage | undefined;
  /** VirtualDaaScoreChangedNotificationMessage virtualDaaScoreChangedNotification = 1076; */
  getBalanceByAddressRequest?: GetBalanceByAddressRequestMessage | undefined;
  getBalancesByAddressesRequest?: GetBalancesByAddressesRequestMessage | undefined;
  notifyNewBlockTemplateRequest?: NotifyNewBlockTemplateRequestMessage | undefined;
  /** NewBlockTemplateNotificationMessage newBlockTemplateNotification = 1083; */
  getMempoolEntriesByAddressesRequest?: GetMempoolEntriesByAddressesRequestMessage | undefined;
  getCoinSupplyRequest?: GetCoinSupplyRequestMessage | undefined;
  pingRequest?: PingRequestMessage | undefined;
  getMetricsRequest?: GetMetricsRequestMessage | undefined;
  getServerInfoRequest?: GetServerInfoRequestMessage | undefined;
  getSyncStatusRequest?: GetSyncStatusRequestMessage | undefined;
  getDaaScoreTimestampEstimateRequest?: GetDaaScoreTimestampEstimateRequestMessage | undefined;
  submitTransactionReplacementRequest?: SubmitTransactionReplacementRequestMessage | undefined;
  getConnectionsRequest?: GetConnectionsRequestMessage | undefined;
  getSystemInfoRequest?: GetSystemInfoRequestMessage | undefined;
  getFeeEstimateRequest?: GetFeeEstimateRequestMessage | undefined;
  getFeeEstimateExperimentalRequest?: GetFeeEstimateExperimentalRequestMessage | undefined;
  getCurrentBlockColorRequest?: GetCurrentBlockColorRequestMessage | undefined;
}

export interface KaspadResponse {
  id: number;
  getCurrentNetworkResponse?: GetCurrentNetworkResponseMessage | undefined;
  submitBlockResponse?: SubmitBlockResponseMessage | undefined;
  getBlockTemplateResponse?: GetBlockTemplateResponseMessage | undefined;
  notifyBlockAddedResponse?: NotifyBlockAddedResponseMessage | undefined;
  blockAddedNotification?: BlockAddedNotificationMessage | undefined;
  getPeerAddressesResponse?: GetPeerAddressesResponseMessage | undefined;
  GetSinkResponse?: GetSinkResponseMessage | undefined;
  getMempoolEntryResponse?: GetMempoolEntryResponseMessage | undefined;
  getConnectedPeerInfoResponse?: GetConnectedPeerInfoResponseMessage | undefined;
  addPeerResponse?: AddPeerResponseMessage | undefined;
  submitTransactionResponse?: SubmitTransactionResponseMessage | undefined;
  notifyVirtualChainChangedResponse?: NotifyVirtualChainChangedResponseMessage | undefined;
  virtualChainChangedNotification?: VirtualChainChangedNotificationMessage | undefined;
  getBlockResponse?: GetBlockResponseMessage | undefined;
  getSubnetworkResponse?: GetSubnetworkResponseMessage | undefined;
  getVirtualChainFromBlockResponse?: GetVirtualChainFromBlockResponseMessage | undefined;
  getBlocksResponse?: GetBlocksResponseMessage | undefined;
  getBlockCountResponse?: GetBlockCountResponseMessage | undefined;
  getBlockDagInfoResponse?: GetBlockDagInfoResponseMessage | undefined;
  resolveFinalityConflictResponse?: ResolveFinalityConflictResponseMessage | undefined;
  notifyFinalityConflictResponse?: NotifyFinalityConflictResponseMessage | undefined;
  finalityConflictNotification?: FinalityConflictNotificationMessage | undefined;
  finalityConflictResolvedNotification?: FinalityConflictResolvedNotificationMessage | undefined;
  getMempoolEntriesResponse?: GetMempoolEntriesResponseMessage | undefined;
  shutdownResponse?: ShutdownResponseMessage | undefined;
  getHeadersResponse?: GetHeadersResponseMessage | undefined;
  notifyUtxosChangedResponse?: NotifyUtxosChangedResponseMessage | undefined;
  utxosChangedNotification?: UtxosChangedNotificationMessage | undefined;
  getUtxosByAddressesResponse?: GetUtxosByAddressesResponseMessage | undefined;
  getSinkBlueScoreResponse?: GetSinkBlueScoreResponseMessage | undefined;
  notifySinkBlueScoreChangedResponse?: NotifySinkBlueScoreChangedResponseMessage | undefined;
  sinkBlueScoreChangedNotification?: SinkBlueScoreChangedNotificationMessage | undefined;
  banResponse?: BanResponseMessage | undefined;
  unbanResponse?: UnbanResponseMessage | undefined;
  getInfoResponse?: GetInfoResponseMessage | undefined;
  stopNotifyingUtxosChangedResponse?: StopNotifyingUtxosChangedResponseMessage | undefined;
  notifyPruningPointUtxoSetOverrideResponse?: NotifyPruningPointUtxoSetOverrideResponseMessage | undefined;
  pruningPointUtxoSetOverrideNotification?: PruningPointUtxoSetOverrideNotificationMessage | undefined;
  stopNotifyingPruningPointUtxoSetOverrideResponse?:
    | StopNotifyingPruningPointUtxoSetOverrideResponseMessage
    | undefined;
  estimateNetworkHashesPerSecondResponse?: EstimateNetworkHashesPerSecondResponseMessage | undefined;
  notifyVirtualDaaScoreChangedResponse?: NotifyVirtualDaaScoreChangedResponseMessage | undefined;
  virtualDaaScoreChangedNotification?: VirtualDaaScoreChangedNotificationMessage | undefined;
  getBalanceByAddressResponse?: GetBalanceByAddressResponseMessage | undefined;
  getBalancesByAddressesResponse?: GetBalancesByAddressesResponseMessage | undefined;
  notifyNewBlockTemplateResponse?: NotifyNewBlockTemplateResponseMessage | undefined;
  newBlockTemplateNotification?: NewBlockTemplateNotificationMessage | undefined;
  getMempoolEntriesByAddressesResponse?: GetMempoolEntriesByAddressesResponseMessage | undefined;
  getCoinSupplyResponse?: GetCoinSupplyResponseMessage | undefined;
  pingResponse?: PingResponseMessage | undefined;
  getMetricsResponse?: GetMetricsResponseMessage | undefined;
  getServerInfoResponse?: GetServerInfoResponseMessage | undefined;
  getSyncStatusResponse?: GetSyncStatusResponseMessage | undefined;
  getDaaScoreTimestampEstimateResponse?: GetDaaScoreTimestampEstimateResponseMessage | undefined;
  submitTransactionReplacementResponse?: SubmitTransactionReplacementResponseMessage | undefined;
  getConnectionsResponse?: GetConnectionsResponseMessage | undefined;
  getSystemInfoResponse?: GetSystemInfoResponseMessage | undefined;
  getFeeEstimateResponse?: GetFeeEstimateResponseMessage | undefined;
  getFeeEstimateExperimentalResponse?: GetFeeEstimateExperimentalResponseMessage | undefined;
  getCurrentBlockColorResponse?: GetCurrentBlockColorResponseMessage | undefined;
}

function createBaseKaspadRequest(): KaspadRequest {
  return {
    id: 0,
    getCurrentNetworkRequest: undefined,
    submitBlockRequest: undefined,
    getBlockTemplateRequest: undefined,
    notifyBlockAddedRequest: undefined,
    getPeerAddressesRequest: undefined,
    GetSinkRequest: undefined,
    getMempoolEntryRequest: undefined,
    getConnectedPeerInfoRequest: undefined,
    addPeerRequest: undefined,
    submitTransactionRequest: undefined,
    notifyVirtualChainChangedRequest: undefined,
    getBlockRequest: undefined,
    getSubnetworkRequest: undefined,
    getVirtualChainFromBlockRequest: undefined,
    getBlocksRequest: undefined,
    getBlockCountRequest: undefined,
    getBlockDagInfoRequest: undefined,
    resolveFinalityConflictRequest: undefined,
    notifyFinalityConflictRequest: undefined,
    getMempoolEntriesRequest: undefined,
    shutdownRequest: undefined,
    getHeadersRequest: undefined,
    notifyUtxosChangedRequest: undefined,
    getUtxosByAddressesRequest: undefined,
    getSinkBlueScoreRequest: undefined,
    notifySinkBlueScoreChangedRequest: undefined,
    banRequest: undefined,
    unbanRequest: undefined,
    getInfoRequest: undefined,
    stopNotifyingUtxosChangedRequest: undefined,
    notifyPruningPointUtxoSetOverrideRequest: undefined,
    stopNotifyingPruningPointUtxoSetOverrideRequest: undefined,
    estimateNetworkHashesPerSecondRequest: undefined,
    notifyVirtualDaaScoreChangedRequest: undefined,
    getBalanceByAddressRequest: undefined,
    getBalancesByAddressesRequest: undefined,
    notifyNewBlockTemplateRequest: undefined,
    getMempoolEntriesByAddressesRequest: undefined,
    getCoinSupplyRequest: undefined,
    pingRequest: undefined,
    getMetricsRequest: undefined,
    getServerInfoRequest: undefined,
    getSyncStatusRequest: undefined,
    getDaaScoreTimestampEstimateRequest: undefined,
    submitTransactionReplacementRequest: undefined,
    getConnectionsRequest: undefined,
    getSystemInfoRequest: undefined,
    getFeeEstimateRequest: undefined,
    getFeeEstimateExperimentalRequest: undefined,
    getCurrentBlockColorRequest: undefined
  };
}

export const KaspadRequest: MessageFns<KaspadRequest> = {
  encode(message: KaspadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(808).uint64(message.id);
    }
    if (message.getCurrentNetworkRequest !== undefined) {
      GetCurrentNetworkRequestMessage.encode(message.getCurrentNetworkRequest, writer.uint32(8010).fork()).join();
    }
    if (message.submitBlockRequest !== undefined) {
      SubmitBlockRequestMessage.encode(message.submitBlockRequest, writer.uint32(8026).fork()).join();
    }
    if (message.getBlockTemplateRequest !== undefined) {
      GetBlockTemplateRequestMessage.encode(message.getBlockTemplateRequest, writer.uint32(8042).fork()).join();
    }
    if (message.notifyBlockAddedRequest !== undefined) {
      NotifyBlockAddedRequestMessage.encode(message.notifyBlockAddedRequest, writer.uint32(8058).fork()).join();
    }
    if (message.getPeerAddressesRequest !== undefined) {
      GetPeerAddressesRequestMessage.encode(message.getPeerAddressesRequest, writer.uint32(8082).fork()).join();
    }
    if (message.GetSinkRequest !== undefined) {
      GetSinkRequestMessage.encode(message.GetSinkRequest, writer.uint32(8098).fork()).join();
    }
    if (message.getMempoolEntryRequest !== undefined) {
      GetMempoolEntryRequestMessage.encode(message.getMempoolEntryRequest, writer.uint32(8114).fork()).join();
    }
    if (message.getConnectedPeerInfoRequest !== undefined) {
      GetConnectedPeerInfoRequestMessage.encode(message.getConnectedPeerInfoRequest, writer.uint32(8130).fork()).join();
    }
    if (message.addPeerRequest !== undefined) {
      AddPeerRequestMessage.encode(message.addPeerRequest, writer.uint32(8146).fork()).join();
    }
    if (message.submitTransactionRequest !== undefined) {
      SubmitTransactionRequestMessage.encode(message.submitTransactionRequest, writer.uint32(8162).fork()).join();
    }
    if (message.notifyVirtualChainChangedRequest !== undefined) {
      NotifyVirtualChainChangedRequestMessage.encode(
        message.notifyVirtualChainChangedRequest,
        writer.uint32(8178).fork()
      ).join();
    }
    if (message.getBlockRequest !== undefined) {
      GetBlockRequestMessage.encode(message.getBlockRequest, writer.uint32(8202).fork()).join();
    }
    if (message.getSubnetworkRequest !== undefined) {
      GetSubnetworkRequestMessage.encode(message.getSubnetworkRequest, writer.uint32(8218).fork()).join();
    }
    if (message.getVirtualChainFromBlockRequest !== undefined) {
      GetVirtualChainFromBlockRequestMessage.encode(
        message.getVirtualChainFromBlockRequest,
        writer.uint32(8234).fork()
      ).join();
    }
    if (message.getBlocksRequest !== undefined) {
      GetBlocksRequestMessage.encode(message.getBlocksRequest, writer.uint32(8250).fork()).join();
    }
    if (message.getBlockCountRequest !== undefined) {
      GetBlockCountRequestMessage.encode(message.getBlockCountRequest, writer.uint32(8266).fork()).join();
    }
    if (message.getBlockDagInfoRequest !== undefined) {
      GetBlockDagInfoRequestMessage.encode(message.getBlockDagInfoRequest, writer.uint32(8282).fork()).join();
    }
    if (message.resolveFinalityConflictRequest !== undefined) {
      ResolveFinalityConflictRequestMessage.encode(
        message.resolveFinalityConflictRequest,
        writer.uint32(8298).fork()
      ).join();
    }
    if (message.notifyFinalityConflictRequest !== undefined) {
      NotifyFinalityConflictRequestMessage.encode(
        message.notifyFinalityConflictRequest,
        writer.uint32(8314).fork()
      ).join();
    }
    if (message.getMempoolEntriesRequest !== undefined) {
      GetMempoolEntriesRequestMessage.encode(message.getMempoolEntriesRequest, writer.uint32(8346).fork()).join();
    }
    if (message.shutdownRequest !== undefined) {
      ShutdownRequestMessage.encode(message.shutdownRequest, writer.uint32(8362).fork()).join();
    }
    if (message.getHeadersRequest !== undefined) {
      GetHeadersRequestMessage.encode(message.getHeadersRequest, writer.uint32(8378).fork()).join();
    }
    if (message.notifyUtxosChangedRequest !== undefined) {
      NotifyUtxosChangedRequestMessage.encode(message.notifyUtxosChangedRequest, writer.uint32(8394).fork()).join();
    }
    if (message.getUtxosByAddressesRequest !== undefined) {
      GetUtxosByAddressesRequestMessage.encode(message.getUtxosByAddressesRequest, writer.uint32(8418).fork()).join();
    }
    if (message.getSinkBlueScoreRequest !== undefined) {
      GetSinkBlueScoreRequestMessage.encode(message.getSinkBlueScoreRequest, writer.uint32(8434).fork()).join();
    }
    if (message.notifySinkBlueScoreChangedRequest !== undefined) {
      NotifySinkBlueScoreChangedRequestMessage.encode(
        message.notifySinkBlueScoreChangedRequest,
        writer.uint32(8450).fork()
      ).join();
    }
    if (message.banRequest !== undefined) {
      BanRequestMessage.encode(message.banRequest, writer.uint32(8474).fork()).join();
    }
    if (message.unbanRequest !== undefined) {
      UnbanRequestMessage.encode(message.unbanRequest, writer.uint32(8490).fork()).join();
    }
    if (message.getInfoRequest !== undefined) {
      GetInfoRequestMessage.encode(message.getInfoRequest, writer.uint32(8506).fork()).join();
    }
    if (message.stopNotifyingUtxosChangedRequest !== undefined) {
      StopNotifyingUtxosChangedRequestMessage.encode(
        message.stopNotifyingUtxosChangedRequest,
        writer.uint32(8522).fork()
      ).join();
    }
    if (message.notifyPruningPointUtxoSetOverrideRequest !== undefined) {
      NotifyPruningPointUtxoSetOverrideRequestMessage.encode(
        message.notifyPruningPointUtxoSetOverrideRequest,
        writer.uint32(8538).fork()
      ).join();
    }
    if (message.stopNotifyingPruningPointUtxoSetOverrideRequest !== undefined) {
      StopNotifyingPruningPointUtxoSetOverrideRequestMessage.encode(
        message.stopNotifyingPruningPointUtxoSetOverrideRequest,
        writer.uint32(8562).fork()
      ).join();
    }
    if (message.estimateNetworkHashesPerSecondRequest !== undefined) {
      EstimateNetworkHashesPerSecondRequestMessage.encode(
        message.estimateNetworkHashesPerSecondRequest,
        writer.uint32(8578).fork()
      ).join();
    }
    if (message.notifyVirtualDaaScoreChangedRequest !== undefined) {
      NotifyVirtualDaaScoreChangedRequestMessage.encode(
        message.notifyVirtualDaaScoreChangedRequest,
        writer.uint32(8594).fork()
      ).join();
    }
    if (message.getBalanceByAddressRequest !== undefined) {
      GetBalanceByAddressRequestMessage.encode(message.getBalanceByAddressRequest, writer.uint32(8618).fork()).join();
    }
    if (message.getBalancesByAddressesRequest !== undefined) {
      GetBalancesByAddressesRequestMessage.encode(
        message.getBalancesByAddressesRequest,
        writer.uint32(8634).fork()
      ).join();
    }
    if (message.notifyNewBlockTemplateRequest !== undefined) {
      NotifyNewBlockTemplateRequestMessage.encode(
        message.notifyNewBlockTemplateRequest,
        writer.uint32(8650).fork()
      ).join();
    }
    if (message.getMempoolEntriesByAddressesRequest !== undefined) {
      GetMempoolEntriesByAddressesRequestMessage.encode(
        message.getMempoolEntriesByAddressesRequest,
        writer.uint32(8674).fork()
      ).join();
    }
    if (message.getCoinSupplyRequest !== undefined) {
      GetCoinSupplyRequestMessage.encode(message.getCoinSupplyRequest, writer.uint32(8690).fork()).join();
    }
    if (message.pingRequest !== undefined) {
      PingRequestMessage.encode(message.pingRequest, writer.uint32(8706).fork()).join();
    }
    if (message.getMetricsRequest !== undefined) {
      GetMetricsRequestMessage.encode(message.getMetricsRequest, writer.uint32(8722).fork()).join();
    }
    if (message.getServerInfoRequest !== undefined) {
      GetServerInfoRequestMessage.encode(message.getServerInfoRequest, writer.uint32(8738).fork()).join();
    }
    if (message.getSyncStatusRequest !== undefined) {
      GetSyncStatusRequestMessage.encode(message.getSyncStatusRequest, writer.uint32(8754).fork()).join();
    }
    if (message.getDaaScoreTimestampEstimateRequest !== undefined) {
      GetDaaScoreTimestampEstimateRequestMessage.encode(
        message.getDaaScoreTimestampEstimateRequest,
        writer.uint32(8770).fork()
      ).join();
    }
    if (message.submitTransactionReplacementRequest !== undefined) {
      SubmitTransactionReplacementRequestMessage.encode(
        message.submitTransactionReplacementRequest,
        writer.uint32(8802).fork()
      ).join();
    }
    if (message.getConnectionsRequest !== undefined) {
      GetConnectionsRequestMessage.encode(message.getConnectionsRequest, writer.uint32(8818).fork()).join();
    }
    if (message.getSystemInfoRequest !== undefined) {
      GetSystemInfoRequestMessage.encode(message.getSystemInfoRequest, writer.uint32(8834).fork()).join();
    }
    if (message.getFeeEstimateRequest !== undefined) {
      GetFeeEstimateRequestMessage.encode(message.getFeeEstimateRequest, writer.uint32(8850).fork()).join();
    }
    if (message.getFeeEstimateExperimentalRequest !== undefined) {
      GetFeeEstimateExperimentalRequestMessage.encode(
        message.getFeeEstimateExperimentalRequest,
        writer.uint32(8866).fork()
      ).join();
    }
    if (message.getCurrentBlockColorRequest !== undefined) {
      GetCurrentBlockColorRequestMessage.encode(message.getCurrentBlockColorRequest, writer.uint32(8882).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KaspadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKaspadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 101: {
          if (tag !== 808) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 1001: {
          if (tag !== 8010) {
            break;
          }

          message.getCurrentNetworkRequest = GetCurrentNetworkRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1003: {
          if (tag !== 8026) {
            break;
          }

          message.submitBlockRequest = SubmitBlockRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1005: {
          if (tag !== 8042) {
            break;
          }

          message.getBlockTemplateRequest = GetBlockTemplateRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1007: {
          if (tag !== 8058) {
            break;
          }

          message.notifyBlockAddedRequest = NotifyBlockAddedRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1010: {
          if (tag !== 8082) {
            break;
          }

          message.getPeerAddressesRequest = GetPeerAddressesRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1012: {
          if (tag !== 8098) {
            break;
          }

          message.GetSinkRequest = GetSinkRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1014: {
          if (tag !== 8114) {
            break;
          }

          message.getMempoolEntryRequest = GetMempoolEntryRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1016: {
          if (tag !== 8130) {
            break;
          }

          message.getConnectedPeerInfoRequest = GetConnectedPeerInfoRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1018: {
          if (tag !== 8146) {
            break;
          }

          message.addPeerRequest = AddPeerRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1020: {
          if (tag !== 8162) {
            break;
          }

          message.submitTransactionRequest = SubmitTransactionRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1022: {
          if (tag !== 8178) {
            break;
          }

          message.notifyVirtualChainChangedRequest = NotifyVirtualChainChangedRequestMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1025: {
          if (tag !== 8202) {
            break;
          }

          message.getBlockRequest = GetBlockRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1027: {
          if (tag !== 8218) {
            break;
          }

          message.getSubnetworkRequest = GetSubnetworkRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1029: {
          if (tag !== 8234) {
            break;
          }

          message.getVirtualChainFromBlockRequest = GetVirtualChainFromBlockRequestMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1031: {
          if (tag !== 8250) {
            break;
          }

          message.getBlocksRequest = GetBlocksRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1033: {
          if (tag !== 8266) {
            break;
          }

          message.getBlockCountRequest = GetBlockCountRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1035: {
          if (tag !== 8282) {
            break;
          }

          message.getBlockDagInfoRequest = GetBlockDagInfoRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1037: {
          if (tag !== 8298) {
            break;
          }

          message.resolveFinalityConflictRequest = ResolveFinalityConflictRequestMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1039: {
          if (tag !== 8314) {
            break;
          }

          message.notifyFinalityConflictRequest = NotifyFinalityConflictRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1043: {
          if (tag !== 8346) {
            break;
          }

          message.getMempoolEntriesRequest = GetMempoolEntriesRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1045: {
          if (tag !== 8362) {
            break;
          }

          message.shutdownRequest = ShutdownRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1047: {
          if (tag !== 8378) {
            break;
          }

          message.getHeadersRequest = GetHeadersRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1049: {
          if (tag !== 8394) {
            break;
          }

          message.notifyUtxosChangedRequest = NotifyUtxosChangedRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1052: {
          if (tag !== 8418) {
            break;
          }

          message.getUtxosByAddressesRequest = GetUtxosByAddressesRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1054: {
          if (tag !== 8434) {
            break;
          }

          message.getSinkBlueScoreRequest = GetSinkBlueScoreRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1056: {
          if (tag !== 8450) {
            break;
          }

          message.notifySinkBlueScoreChangedRequest = NotifySinkBlueScoreChangedRequestMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1059: {
          if (tag !== 8474) {
            break;
          }

          message.banRequest = BanRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1061: {
          if (tag !== 8490) {
            break;
          }

          message.unbanRequest = UnbanRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1063: {
          if (tag !== 8506) {
            break;
          }

          message.getInfoRequest = GetInfoRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1065: {
          if (tag !== 8522) {
            break;
          }

          message.stopNotifyingUtxosChangedRequest = StopNotifyingUtxosChangedRequestMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1067: {
          if (tag !== 8538) {
            break;
          }

          message.notifyPruningPointUtxoSetOverrideRequest = NotifyPruningPointUtxoSetOverrideRequestMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1070: {
          if (tag !== 8562) {
            break;
          }

          message.stopNotifyingPruningPointUtxoSetOverrideRequest =
            StopNotifyingPruningPointUtxoSetOverrideRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1072: {
          if (tag !== 8578) {
            break;
          }

          message.estimateNetworkHashesPerSecondRequest = EstimateNetworkHashesPerSecondRequestMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1074: {
          if (tag !== 8594) {
            break;
          }

          message.notifyVirtualDaaScoreChangedRequest = NotifyVirtualDaaScoreChangedRequestMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1077: {
          if (tag !== 8618) {
            break;
          }

          message.getBalanceByAddressRequest = GetBalanceByAddressRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1079: {
          if (tag !== 8634) {
            break;
          }

          message.getBalancesByAddressesRequest = GetBalancesByAddressesRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1081: {
          if (tag !== 8650) {
            break;
          }

          message.notifyNewBlockTemplateRequest = NotifyNewBlockTemplateRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1084: {
          if (tag !== 8674) {
            break;
          }

          message.getMempoolEntriesByAddressesRequest = GetMempoolEntriesByAddressesRequestMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1086: {
          if (tag !== 8690) {
            break;
          }

          message.getCoinSupplyRequest = GetCoinSupplyRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1088: {
          if (tag !== 8706) {
            break;
          }

          message.pingRequest = PingRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1090: {
          if (tag !== 8722) {
            break;
          }

          message.getMetricsRequest = GetMetricsRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1092: {
          if (tag !== 8738) {
            break;
          }

          message.getServerInfoRequest = GetServerInfoRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1094: {
          if (tag !== 8754) {
            break;
          }

          message.getSyncStatusRequest = GetSyncStatusRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1096: {
          if (tag !== 8770) {
            break;
          }

          message.getDaaScoreTimestampEstimateRequest = GetDaaScoreTimestampEstimateRequestMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1100: {
          if (tag !== 8802) {
            break;
          }

          message.submitTransactionReplacementRequest = SubmitTransactionReplacementRequestMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1102: {
          if (tag !== 8818) {
            break;
          }

          message.getConnectionsRequest = GetConnectionsRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1104: {
          if (tag !== 8834) {
            break;
          }

          message.getSystemInfoRequest = GetSystemInfoRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1106: {
          if (tag !== 8850) {
            break;
          }

          message.getFeeEstimateRequest = GetFeeEstimateRequestMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1108: {
          if (tag !== 8866) {
            break;
          }

          message.getFeeEstimateExperimentalRequest = GetFeeEstimateExperimentalRequestMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1110: {
          if (tag !== 8882) {
            break;
          }

          message.getCurrentBlockColorRequest = GetCurrentBlockColorRequestMessage.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<KaspadRequest>): KaspadRequest {
    return KaspadRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<KaspadRequest>): KaspadRequest {
    const message = createBaseKaspadRequest();
    message.id = object.id ?? 0;
    message.getCurrentNetworkRequest =
      object.getCurrentNetworkRequest !== undefined && object.getCurrentNetworkRequest !== null
        ? GetCurrentNetworkRequestMessage.fromPartial(object.getCurrentNetworkRequest)
        : undefined;
    message.submitBlockRequest =
      object.submitBlockRequest !== undefined && object.submitBlockRequest !== null
        ? SubmitBlockRequestMessage.fromPartial(object.submitBlockRequest)
        : undefined;
    message.getBlockTemplateRequest =
      object.getBlockTemplateRequest !== undefined && object.getBlockTemplateRequest !== null
        ? GetBlockTemplateRequestMessage.fromPartial(object.getBlockTemplateRequest)
        : undefined;
    message.notifyBlockAddedRequest =
      object.notifyBlockAddedRequest !== undefined && object.notifyBlockAddedRequest !== null
        ? NotifyBlockAddedRequestMessage.fromPartial(object.notifyBlockAddedRequest)
        : undefined;
    message.getPeerAddressesRequest =
      object.getPeerAddressesRequest !== undefined && object.getPeerAddressesRequest !== null
        ? GetPeerAddressesRequestMessage.fromPartial(object.getPeerAddressesRequest)
        : undefined;
    message.GetSinkRequest =
      object.GetSinkRequest !== undefined && object.GetSinkRequest !== null
        ? GetSinkRequestMessage.fromPartial(object.GetSinkRequest)
        : undefined;
    message.getMempoolEntryRequest =
      object.getMempoolEntryRequest !== undefined && object.getMempoolEntryRequest !== null
        ? GetMempoolEntryRequestMessage.fromPartial(object.getMempoolEntryRequest)
        : undefined;
    message.getConnectedPeerInfoRequest =
      object.getConnectedPeerInfoRequest !== undefined && object.getConnectedPeerInfoRequest !== null
        ? GetConnectedPeerInfoRequestMessage.fromPartial(object.getConnectedPeerInfoRequest)
        : undefined;
    message.addPeerRequest =
      object.addPeerRequest !== undefined && object.addPeerRequest !== null
        ? AddPeerRequestMessage.fromPartial(object.addPeerRequest)
        : undefined;
    message.submitTransactionRequest =
      object.submitTransactionRequest !== undefined && object.submitTransactionRequest !== null
        ? SubmitTransactionRequestMessage.fromPartial(object.submitTransactionRequest)
        : undefined;
    message.notifyVirtualChainChangedRequest =
      object.notifyVirtualChainChangedRequest !== undefined && object.notifyVirtualChainChangedRequest !== null
        ? NotifyVirtualChainChangedRequestMessage.fromPartial(object.notifyVirtualChainChangedRequest)
        : undefined;
    message.getBlockRequest =
      object.getBlockRequest !== undefined && object.getBlockRequest !== null
        ? GetBlockRequestMessage.fromPartial(object.getBlockRequest)
        : undefined;
    message.getSubnetworkRequest =
      object.getSubnetworkRequest !== undefined && object.getSubnetworkRequest !== null
        ? GetSubnetworkRequestMessage.fromPartial(object.getSubnetworkRequest)
        : undefined;
    message.getVirtualChainFromBlockRequest =
      object.getVirtualChainFromBlockRequest !== undefined && object.getVirtualChainFromBlockRequest !== null
        ? GetVirtualChainFromBlockRequestMessage.fromPartial(object.getVirtualChainFromBlockRequest)
        : undefined;
    message.getBlocksRequest =
      object.getBlocksRequest !== undefined && object.getBlocksRequest !== null
        ? GetBlocksRequestMessage.fromPartial(object.getBlocksRequest)
        : undefined;
    message.getBlockCountRequest =
      object.getBlockCountRequest !== undefined && object.getBlockCountRequest !== null
        ? GetBlockCountRequestMessage.fromPartial(object.getBlockCountRequest)
        : undefined;
    message.getBlockDagInfoRequest =
      object.getBlockDagInfoRequest !== undefined && object.getBlockDagInfoRequest !== null
        ? GetBlockDagInfoRequestMessage.fromPartial(object.getBlockDagInfoRequest)
        : undefined;
    message.resolveFinalityConflictRequest =
      object.resolveFinalityConflictRequest !== undefined && object.resolveFinalityConflictRequest !== null
        ? ResolveFinalityConflictRequestMessage.fromPartial(object.resolveFinalityConflictRequest)
        : undefined;
    message.notifyFinalityConflictRequest =
      object.notifyFinalityConflictRequest !== undefined && object.notifyFinalityConflictRequest !== null
        ? NotifyFinalityConflictRequestMessage.fromPartial(object.notifyFinalityConflictRequest)
        : undefined;
    message.getMempoolEntriesRequest =
      object.getMempoolEntriesRequest !== undefined && object.getMempoolEntriesRequest !== null
        ? GetMempoolEntriesRequestMessage.fromPartial(object.getMempoolEntriesRequest)
        : undefined;
    message.shutdownRequest =
      object.shutdownRequest !== undefined && object.shutdownRequest !== null
        ? ShutdownRequestMessage.fromPartial(object.shutdownRequest)
        : undefined;
    message.getHeadersRequest =
      object.getHeadersRequest !== undefined && object.getHeadersRequest !== null
        ? GetHeadersRequestMessage.fromPartial(object.getHeadersRequest)
        : undefined;
    message.notifyUtxosChangedRequest =
      object.notifyUtxosChangedRequest !== undefined && object.notifyUtxosChangedRequest !== null
        ? NotifyUtxosChangedRequestMessage.fromPartial(object.notifyUtxosChangedRequest)
        : undefined;
    message.getUtxosByAddressesRequest =
      object.getUtxosByAddressesRequest !== undefined && object.getUtxosByAddressesRequest !== null
        ? GetUtxosByAddressesRequestMessage.fromPartial(object.getUtxosByAddressesRequest)
        : undefined;
    message.getSinkBlueScoreRequest =
      object.getSinkBlueScoreRequest !== undefined && object.getSinkBlueScoreRequest !== null
        ? GetSinkBlueScoreRequestMessage.fromPartial(object.getSinkBlueScoreRequest)
        : undefined;
    message.notifySinkBlueScoreChangedRequest =
      object.notifySinkBlueScoreChangedRequest !== undefined && object.notifySinkBlueScoreChangedRequest !== null
        ? NotifySinkBlueScoreChangedRequestMessage.fromPartial(object.notifySinkBlueScoreChangedRequest)
        : undefined;
    message.banRequest =
      object.banRequest !== undefined && object.banRequest !== null
        ? BanRequestMessage.fromPartial(object.banRequest)
        : undefined;
    message.unbanRequest =
      object.unbanRequest !== undefined && object.unbanRequest !== null
        ? UnbanRequestMessage.fromPartial(object.unbanRequest)
        : undefined;
    message.getInfoRequest =
      object.getInfoRequest !== undefined && object.getInfoRequest !== null
        ? GetInfoRequestMessage.fromPartial(object.getInfoRequest)
        : undefined;
    message.stopNotifyingUtxosChangedRequest =
      object.stopNotifyingUtxosChangedRequest !== undefined && object.stopNotifyingUtxosChangedRequest !== null
        ? StopNotifyingUtxosChangedRequestMessage.fromPartial(object.stopNotifyingUtxosChangedRequest)
        : undefined;
    message.notifyPruningPointUtxoSetOverrideRequest =
      object.notifyPruningPointUtxoSetOverrideRequest !== undefined &&
      object.notifyPruningPointUtxoSetOverrideRequest !== null
        ? NotifyPruningPointUtxoSetOverrideRequestMessage.fromPartial(object.notifyPruningPointUtxoSetOverrideRequest)
        : undefined;
    message.stopNotifyingPruningPointUtxoSetOverrideRequest =
      object.stopNotifyingPruningPointUtxoSetOverrideRequest !== undefined &&
      object.stopNotifyingPruningPointUtxoSetOverrideRequest !== null
        ? StopNotifyingPruningPointUtxoSetOverrideRequestMessage.fromPartial(
            object.stopNotifyingPruningPointUtxoSetOverrideRequest
          )
        : undefined;
    message.estimateNetworkHashesPerSecondRequest =
      object.estimateNetworkHashesPerSecondRequest !== undefined &&
      object.estimateNetworkHashesPerSecondRequest !== null
        ? EstimateNetworkHashesPerSecondRequestMessage.fromPartial(object.estimateNetworkHashesPerSecondRequest)
        : undefined;
    message.notifyVirtualDaaScoreChangedRequest =
      object.notifyVirtualDaaScoreChangedRequest !== undefined && object.notifyVirtualDaaScoreChangedRequest !== null
        ? NotifyVirtualDaaScoreChangedRequestMessage.fromPartial(object.notifyVirtualDaaScoreChangedRequest)
        : undefined;
    message.getBalanceByAddressRequest =
      object.getBalanceByAddressRequest !== undefined && object.getBalanceByAddressRequest !== null
        ? GetBalanceByAddressRequestMessage.fromPartial(object.getBalanceByAddressRequest)
        : undefined;
    message.getBalancesByAddressesRequest =
      object.getBalancesByAddressesRequest !== undefined && object.getBalancesByAddressesRequest !== null
        ? GetBalancesByAddressesRequestMessage.fromPartial(object.getBalancesByAddressesRequest)
        : undefined;
    message.notifyNewBlockTemplateRequest =
      object.notifyNewBlockTemplateRequest !== undefined && object.notifyNewBlockTemplateRequest !== null
        ? NotifyNewBlockTemplateRequestMessage.fromPartial(object.notifyNewBlockTemplateRequest)
        : undefined;
    message.getMempoolEntriesByAddressesRequest =
      object.getMempoolEntriesByAddressesRequest !== undefined && object.getMempoolEntriesByAddressesRequest !== null
        ? GetMempoolEntriesByAddressesRequestMessage.fromPartial(object.getMempoolEntriesByAddressesRequest)
        : undefined;
    message.getCoinSupplyRequest =
      object.getCoinSupplyRequest !== undefined && object.getCoinSupplyRequest !== null
        ? GetCoinSupplyRequestMessage.fromPartial(object.getCoinSupplyRequest)
        : undefined;
    message.pingRequest =
      object.pingRequest !== undefined && object.pingRequest !== null
        ? PingRequestMessage.fromPartial(object.pingRequest)
        : undefined;
    message.getMetricsRequest =
      object.getMetricsRequest !== undefined && object.getMetricsRequest !== null
        ? GetMetricsRequestMessage.fromPartial(object.getMetricsRequest)
        : undefined;
    message.getServerInfoRequest =
      object.getServerInfoRequest !== undefined && object.getServerInfoRequest !== null
        ? GetServerInfoRequestMessage.fromPartial(object.getServerInfoRequest)
        : undefined;
    message.getSyncStatusRequest =
      object.getSyncStatusRequest !== undefined && object.getSyncStatusRequest !== null
        ? GetSyncStatusRequestMessage.fromPartial(object.getSyncStatusRequest)
        : undefined;
    message.getDaaScoreTimestampEstimateRequest =
      object.getDaaScoreTimestampEstimateRequest !== undefined && object.getDaaScoreTimestampEstimateRequest !== null
        ? GetDaaScoreTimestampEstimateRequestMessage.fromPartial(object.getDaaScoreTimestampEstimateRequest)
        : undefined;
    message.submitTransactionReplacementRequest =
      object.submitTransactionReplacementRequest !== undefined && object.submitTransactionReplacementRequest !== null
        ? SubmitTransactionReplacementRequestMessage.fromPartial(object.submitTransactionReplacementRequest)
        : undefined;
    message.getConnectionsRequest =
      object.getConnectionsRequest !== undefined && object.getConnectionsRequest !== null
        ? GetConnectionsRequestMessage.fromPartial(object.getConnectionsRequest)
        : undefined;
    message.getSystemInfoRequest =
      object.getSystemInfoRequest !== undefined && object.getSystemInfoRequest !== null
        ? GetSystemInfoRequestMessage.fromPartial(object.getSystemInfoRequest)
        : undefined;
    message.getFeeEstimateRequest =
      object.getFeeEstimateRequest !== undefined && object.getFeeEstimateRequest !== null
        ? GetFeeEstimateRequestMessage.fromPartial(object.getFeeEstimateRequest)
        : undefined;
    message.getFeeEstimateExperimentalRequest =
      object.getFeeEstimateExperimentalRequest !== undefined && object.getFeeEstimateExperimentalRequest !== null
        ? GetFeeEstimateExperimentalRequestMessage.fromPartial(object.getFeeEstimateExperimentalRequest)
        : undefined;
    message.getCurrentBlockColorRequest =
      object.getCurrentBlockColorRequest !== undefined && object.getCurrentBlockColorRequest !== null
        ? GetCurrentBlockColorRequestMessage.fromPartial(object.getCurrentBlockColorRequest)
        : undefined;
    return message;
  }
};

function createBaseKaspadResponse(): KaspadResponse {
  return {
    id: 0,
    getCurrentNetworkResponse: undefined,
    submitBlockResponse: undefined,
    getBlockTemplateResponse: undefined,
    notifyBlockAddedResponse: undefined,
    blockAddedNotification: undefined,
    getPeerAddressesResponse: undefined,
    GetSinkResponse: undefined,
    getMempoolEntryResponse: undefined,
    getConnectedPeerInfoResponse: undefined,
    addPeerResponse: undefined,
    submitTransactionResponse: undefined,
    notifyVirtualChainChangedResponse: undefined,
    virtualChainChangedNotification: undefined,
    getBlockResponse: undefined,
    getSubnetworkResponse: undefined,
    getVirtualChainFromBlockResponse: undefined,
    getBlocksResponse: undefined,
    getBlockCountResponse: undefined,
    getBlockDagInfoResponse: undefined,
    resolveFinalityConflictResponse: undefined,
    notifyFinalityConflictResponse: undefined,
    finalityConflictNotification: undefined,
    finalityConflictResolvedNotification: undefined,
    getMempoolEntriesResponse: undefined,
    shutdownResponse: undefined,
    getHeadersResponse: undefined,
    notifyUtxosChangedResponse: undefined,
    utxosChangedNotification: undefined,
    getUtxosByAddressesResponse: undefined,
    getSinkBlueScoreResponse: undefined,
    notifySinkBlueScoreChangedResponse: undefined,
    sinkBlueScoreChangedNotification: undefined,
    banResponse: undefined,
    unbanResponse: undefined,
    getInfoResponse: undefined,
    stopNotifyingUtxosChangedResponse: undefined,
    notifyPruningPointUtxoSetOverrideResponse: undefined,
    pruningPointUtxoSetOverrideNotification: undefined,
    stopNotifyingPruningPointUtxoSetOverrideResponse: undefined,
    estimateNetworkHashesPerSecondResponse: undefined,
    notifyVirtualDaaScoreChangedResponse: undefined,
    virtualDaaScoreChangedNotification: undefined,
    getBalanceByAddressResponse: undefined,
    getBalancesByAddressesResponse: undefined,
    notifyNewBlockTemplateResponse: undefined,
    newBlockTemplateNotification: undefined,
    getMempoolEntriesByAddressesResponse: undefined,
    getCoinSupplyResponse: undefined,
    pingResponse: undefined,
    getMetricsResponse: undefined,
    getServerInfoResponse: undefined,
    getSyncStatusResponse: undefined,
    getDaaScoreTimestampEstimateResponse: undefined,
    submitTransactionReplacementResponse: undefined,
    getConnectionsResponse: undefined,
    getSystemInfoResponse: undefined,
    getFeeEstimateResponse: undefined,
    getFeeEstimateExperimentalResponse: undefined,
    getCurrentBlockColorResponse: undefined
  };
}

export const KaspadResponse: MessageFns<KaspadResponse> = {
  encode(message: KaspadResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(808).uint64(message.id);
    }
    if (message.getCurrentNetworkResponse !== undefined) {
      GetCurrentNetworkResponseMessage.encode(message.getCurrentNetworkResponse, writer.uint32(8018).fork()).join();
    }
    if (message.submitBlockResponse !== undefined) {
      SubmitBlockResponseMessage.encode(message.submitBlockResponse, writer.uint32(8034).fork()).join();
    }
    if (message.getBlockTemplateResponse !== undefined) {
      GetBlockTemplateResponseMessage.encode(message.getBlockTemplateResponse, writer.uint32(8050).fork()).join();
    }
    if (message.notifyBlockAddedResponse !== undefined) {
      NotifyBlockAddedResponseMessage.encode(message.notifyBlockAddedResponse, writer.uint32(8066).fork()).join();
    }
    if (message.blockAddedNotification !== undefined) {
      BlockAddedNotificationMessage.encode(message.blockAddedNotification, writer.uint32(8074).fork()).join();
    }
    if (message.getPeerAddressesResponse !== undefined) {
      GetPeerAddressesResponseMessage.encode(message.getPeerAddressesResponse, writer.uint32(8090).fork()).join();
    }
    if (message.GetSinkResponse !== undefined) {
      GetSinkResponseMessage.encode(message.GetSinkResponse, writer.uint32(8106).fork()).join();
    }
    if (message.getMempoolEntryResponse !== undefined) {
      GetMempoolEntryResponseMessage.encode(message.getMempoolEntryResponse, writer.uint32(8122).fork()).join();
    }
    if (message.getConnectedPeerInfoResponse !== undefined) {
      GetConnectedPeerInfoResponseMessage.encode(
        message.getConnectedPeerInfoResponse,
        writer.uint32(8138).fork()
      ).join();
    }
    if (message.addPeerResponse !== undefined) {
      AddPeerResponseMessage.encode(message.addPeerResponse, writer.uint32(8154).fork()).join();
    }
    if (message.submitTransactionResponse !== undefined) {
      SubmitTransactionResponseMessage.encode(message.submitTransactionResponse, writer.uint32(8170).fork()).join();
    }
    if (message.notifyVirtualChainChangedResponse !== undefined) {
      NotifyVirtualChainChangedResponseMessage.encode(
        message.notifyVirtualChainChangedResponse,
        writer.uint32(8186).fork()
      ).join();
    }
    if (message.virtualChainChangedNotification !== undefined) {
      VirtualChainChangedNotificationMessage.encode(
        message.virtualChainChangedNotification,
        writer.uint32(8194).fork()
      ).join();
    }
    if (message.getBlockResponse !== undefined) {
      GetBlockResponseMessage.encode(message.getBlockResponse, writer.uint32(8210).fork()).join();
    }
    if (message.getSubnetworkResponse !== undefined) {
      GetSubnetworkResponseMessage.encode(message.getSubnetworkResponse, writer.uint32(8226).fork()).join();
    }
    if (message.getVirtualChainFromBlockResponse !== undefined) {
      GetVirtualChainFromBlockResponseMessage.encode(
        message.getVirtualChainFromBlockResponse,
        writer.uint32(8242).fork()
      ).join();
    }
    if (message.getBlocksResponse !== undefined) {
      GetBlocksResponseMessage.encode(message.getBlocksResponse, writer.uint32(8258).fork()).join();
    }
    if (message.getBlockCountResponse !== undefined) {
      GetBlockCountResponseMessage.encode(message.getBlockCountResponse, writer.uint32(8274).fork()).join();
    }
    if (message.getBlockDagInfoResponse !== undefined) {
      GetBlockDagInfoResponseMessage.encode(message.getBlockDagInfoResponse, writer.uint32(8290).fork()).join();
    }
    if (message.resolveFinalityConflictResponse !== undefined) {
      ResolveFinalityConflictResponseMessage.encode(
        message.resolveFinalityConflictResponse,
        writer.uint32(8306).fork()
      ).join();
    }
    if (message.notifyFinalityConflictResponse !== undefined) {
      NotifyFinalityConflictResponseMessage.encode(
        message.notifyFinalityConflictResponse,
        writer.uint32(8322).fork()
      ).join();
    }
    if (message.finalityConflictNotification !== undefined) {
      FinalityConflictNotificationMessage.encode(
        message.finalityConflictNotification,
        writer.uint32(8330).fork()
      ).join();
    }
    if (message.finalityConflictResolvedNotification !== undefined) {
      FinalityConflictResolvedNotificationMessage.encode(
        message.finalityConflictResolvedNotification,
        writer.uint32(8338).fork()
      ).join();
    }
    if (message.getMempoolEntriesResponse !== undefined) {
      GetMempoolEntriesResponseMessage.encode(message.getMempoolEntriesResponse, writer.uint32(8354).fork()).join();
    }
    if (message.shutdownResponse !== undefined) {
      ShutdownResponseMessage.encode(message.shutdownResponse, writer.uint32(8370).fork()).join();
    }
    if (message.getHeadersResponse !== undefined) {
      GetHeadersResponseMessage.encode(message.getHeadersResponse, writer.uint32(8386).fork()).join();
    }
    if (message.notifyUtxosChangedResponse !== undefined) {
      NotifyUtxosChangedResponseMessage.encode(message.notifyUtxosChangedResponse, writer.uint32(8402).fork()).join();
    }
    if (message.utxosChangedNotification !== undefined) {
      UtxosChangedNotificationMessage.encode(message.utxosChangedNotification, writer.uint32(8410).fork()).join();
    }
    if (message.getUtxosByAddressesResponse !== undefined) {
      GetUtxosByAddressesResponseMessage.encode(message.getUtxosByAddressesResponse, writer.uint32(8426).fork()).join();
    }
    if (message.getSinkBlueScoreResponse !== undefined) {
      GetSinkBlueScoreResponseMessage.encode(message.getSinkBlueScoreResponse, writer.uint32(8442).fork()).join();
    }
    if (message.notifySinkBlueScoreChangedResponse !== undefined) {
      NotifySinkBlueScoreChangedResponseMessage.encode(
        message.notifySinkBlueScoreChangedResponse,
        writer.uint32(8458).fork()
      ).join();
    }
    if (message.sinkBlueScoreChangedNotification !== undefined) {
      SinkBlueScoreChangedNotificationMessage.encode(
        message.sinkBlueScoreChangedNotification,
        writer.uint32(8466).fork()
      ).join();
    }
    if (message.banResponse !== undefined) {
      BanResponseMessage.encode(message.banResponse, writer.uint32(8482).fork()).join();
    }
    if (message.unbanResponse !== undefined) {
      UnbanResponseMessage.encode(message.unbanResponse, writer.uint32(8498).fork()).join();
    }
    if (message.getInfoResponse !== undefined) {
      GetInfoResponseMessage.encode(message.getInfoResponse, writer.uint32(8514).fork()).join();
    }
    if (message.stopNotifyingUtxosChangedResponse !== undefined) {
      StopNotifyingUtxosChangedResponseMessage.encode(
        message.stopNotifyingUtxosChangedResponse,
        writer.uint32(8530).fork()
      ).join();
    }
    if (message.notifyPruningPointUtxoSetOverrideResponse !== undefined) {
      NotifyPruningPointUtxoSetOverrideResponseMessage.encode(
        message.notifyPruningPointUtxoSetOverrideResponse,
        writer.uint32(8546).fork()
      ).join();
    }
    if (message.pruningPointUtxoSetOverrideNotification !== undefined) {
      PruningPointUtxoSetOverrideNotificationMessage.encode(
        message.pruningPointUtxoSetOverrideNotification,
        writer.uint32(8554).fork()
      ).join();
    }
    if (message.stopNotifyingPruningPointUtxoSetOverrideResponse !== undefined) {
      StopNotifyingPruningPointUtxoSetOverrideResponseMessage.encode(
        message.stopNotifyingPruningPointUtxoSetOverrideResponse,
        writer.uint32(8570).fork()
      ).join();
    }
    if (message.estimateNetworkHashesPerSecondResponse !== undefined) {
      EstimateNetworkHashesPerSecondResponseMessage.encode(
        message.estimateNetworkHashesPerSecondResponse,
        writer.uint32(8586).fork()
      ).join();
    }
    if (message.notifyVirtualDaaScoreChangedResponse !== undefined) {
      NotifyVirtualDaaScoreChangedResponseMessage.encode(
        message.notifyVirtualDaaScoreChangedResponse,
        writer.uint32(8602).fork()
      ).join();
    }
    if (message.virtualDaaScoreChangedNotification !== undefined) {
      VirtualDaaScoreChangedNotificationMessage.encode(
        message.virtualDaaScoreChangedNotification,
        writer.uint32(8610).fork()
      ).join();
    }
    if (message.getBalanceByAddressResponse !== undefined) {
      GetBalanceByAddressResponseMessage.encode(message.getBalanceByAddressResponse, writer.uint32(8626).fork()).join();
    }
    if (message.getBalancesByAddressesResponse !== undefined) {
      GetBalancesByAddressesResponseMessage.encode(
        message.getBalancesByAddressesResponse,
        writer.uint32(8642).fork()
      ).join();
    }
    if (message.notifyNewBlockTemplateResponse !== undefined) {
      NotifyNewBlockTemplateResponseMessage.encode(
        message.notifyNewBlockTemplateResponse,
        writer.uint32(8658).fork()
      ).join();
    }
    if (message.newBlockTemplateNotification !== undefined) {
      NewBlockTemplateNotificationMessage.encode(
        message.newBlockTemplateNotification,
        writer.uint32(8666).fork()
      ).join();
    }
    if (message.getMempoolEntriesByAddressesResponse !== undefined) {
      GetMempoolEntriesByAddressesResponseMessage.encode(
        message.getMempoolEntriesByAddressesResponse,
        writer.uint32(8682).fork()
      ).join();
    }
    if (message.getCoinSupplyResponse !== undefined) {
      GetCoinSupplyResponseMessage.encode(message.getCoinSupplyResponse, writer.uint32(8698).fork()).join();
    }
    if (message.pingResponse !== undefined) {
      PingResponseMessage.encode(message.pingResponse, writer.uint32(8714).fork()).join();
    }
    if (message.getMetricsResponse !== undefined) {
      GetMetricsResponseMessage.encode(message.getMetricsResponse, writer.uint32(8730).fork()).join();
    }
    if (message.getServerInfoResponse !== undefined) {
      GetServerInfoResponseMessage.encode(message.getServerInfoResponse, writer.uint32(8746).fork()).join();
    }
    if (message.getSyncStatusResponse !== undefined) {
      GetSyncStatusResponseMessage.encode(message.getSyncStatusResponse, writer.uint32(8762).fork()).join();
    }
    if (message.getDaaScoreTimestampEstimateResponse !== undefined) {
      GetDaaScoreTimestampEstimateResponseMessage.encode(
        message.getDaaScoreTimestampEstimateResponse,
        writer.uint32(8778).fork()
      ).join();
    }
    if (message.submitTransactionReplacementResponse !== undefined) {
      SubmitTransactionReplacementResponseMessage.encode(
        message.submitTransactionReplacementResponse,
        writer.uint32(8810).fork()
      ).join();
    }
    if (message.getConnectionsResponse !== undefined) {
      GetConnectionsResponseMessage.encode(message.getConnectionsResponse, writer.uint32(8826).fork()).join();
    }
    if (message.getSystemInfoResponse !== undefined) {
      GetSystemInfoResponseMessage.encode(message.getSystemInfoResponse, writer.uint32(8842).fork()).join();
    }
    if (message.getFeeEstimateResponse !== undefined) {
      GetFeeEstimateResponseMessage.encode(message.getFeeEstimateResponse, writer.uint32(8858).fork()).join();
    }
    if (message.getFeeEstimateExperimentalResponse !== undefined) {
      GetFeeEstimateExperimentalResponseMessage.encode(
        message.getFeeEstimateExperimentalResponse,
        writer.uint32(8874).fork()
      ).join();
    }
    if (message.getCurrentBlockColorResponse !== undefined) {
      GetCurrentBlockColorResponseMessage.encode(
        message.getCurrentBlockColorResponse,
        writer.uint32(8890).fork()
      ).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KaspadResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKaspadResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 101: {
          if (tag !== 808) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 1002: {
          if (tag !== 8018) {
            break;
          }

          message.getCurrentNetworkResponse = GetCurrentNetworkResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1004: {
          if (tag !== 8034) {
            break;
          }

          message.submitBlockResponse = SubmitBlockResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1006: {
          if (tag !== 8050) {
            break;
          }

          message.getBlockTemplateResponse = GetBlockTemplateResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1008: {
          if (tag !== 8066) {
            break;
          }

          message.notifyBlockAddedResponse = NotifyBlockAddedResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1009: {
          if (tag !== 8074) {
            break;
          }

          message.blockAddedNotification = BlockAddedNotificationMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1011: {
          if (tag !== 8090) {
            break;
          }

          message.getPeerAddressesResponse = GetPeerAddressesResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1013: {
          if (tag !== 8106) {
            break;
          }

          message.GetSinkResponse = GetSinkResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1015: {
          if (tag !== 8122) {
            break;
          }

          message.getMempoolEntryResponse = GetMempoolEntryResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1017: {
          if (tag !== 8138) {
            break;
          }

          message.getConnectedPeerInfoResponse = GetConnectedPeerInfoResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1019: {
          if (tag !== 8154) {
            break;
          }

          message.addPeerResponse = AddPeerResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1021: {
          if (tag !== 8170) {
            break;
          }

          message.submitTransactionResponse = SubmitTransactionResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1023: {
          if (tag !== 8186) {
            break;
          }

          message.notifyVirtualChainChangedResponse = NotifyVirtualChainChangedResponseMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1024: {
          if (tag !== 8194) {
            break;
          }

          message.virtualChainChangedNotification = VirtualChainChangedNotificationMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1026: {
          if (tag !== 8210) {
            break;
          }

          message.getBlockResponse = GetBlockResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1028: {
          if (tag !== 8226) {
            break;
          }

          message.getSubnetworkResponse = GetSubnetworkResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1030: {
          if (tag !== 8242) {
            break;
          }

          message.getVirtualChainFromBlockResponse = GetVirtualChainFromBlockResponseMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1032: {
          if (tag !== 8258) {
            break;
          }

          message.getBlocksResponse = GetBlocksResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1034: {
          if (tag !== 8274) {
            break;
          }

          message.getBlockCountResponse = GetBlockCountResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1036: {
          if (tag !== 8290) {
            break;
          }

          message.getBlockDagInfoResponse = GetBlockDagInfoResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1038: {
          if (tag !== 8306) {
            break;
          }

          message.resolveFinalityConflictResponse = ResolveFinalityConflictResponseMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1040: {
          if (tag !== 8322) {
            break;
          }

          message.notifyFinalityConflictResponse = NotifyFinalityConflictResponseMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1041: {
          if (tag !== 8330) {
            break;
          }

          message.finalityConflictNotification = FinalityConflictNotificationMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1042: {
          if (tag !== 8338) {
            break;
          }

          message.finalityConflictResolvedNotification = FinalityConflictResolvedNotificationMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1044: {
          if (tag !== 8354) {
            break;
          }

          message.getMempoolEntriesResponse = GetMempoolEntriesResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1046: {
          if (tag !== 8370) {
            break;
          }

          message.shutdownResponse = ShutdownResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1048: {
          if (tag !== 8386) {
            break;
          }

          message.getHeadersResponse = GetHeadersResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1050: {
          if (tag !== 8402) {
            break;
          }

          message.notifyUtxosChangedResponse = NotifyUtxosChangedResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1051: {
          if (tag !== 8410) {
            break;
          }

          message.utxosChangedNotification = UtxosChangedNotificationMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1053: {
          if (tag !== 8426) {
            break;
          }

          message.getUtxosByAddressesResponse = GetUtxosByAddressesResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1055: {
          if (tag !== 8442) {
            break;
          }

          message.getSinkBlueScoreResponse = GetSinkBlueScoreResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1057: {
          if (tag !== 8458) {
            break;
          }

          message.notifySinkBlueScoreChangedResponse = NotifySinkBlueScoreChangedResponseMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1058: {
          if (tag !== 8466) {
            break;
          }

          message.sinkBlueScoreChangedNotification = SinkBlueScoreChangedNotificationMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1060: {
          if (tag !== 8482) {
            break;
          }

          message.banResponse = BanResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1062: {
          if (tag !== 8498) {
            break;
          }

          message.unbanResponse = UnbanResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1064: {
          if (tag !== 8514) {
            break;
          }

          message.getInfoResponse = GetInfoResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1066: {
          if (tag !== 8530) {
            break;
          }

          message.stopNotifyingUtxosChangedResponse = StopNotifyingUtxosChangedResponseMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1068: {
          if (tag !== 8546) {
            break;
          }

          message.notifyPruningPointUtxoSetOverrideResponse = NotifyPruningPointUtxoSetOverrideResponseMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1069: {
          if (tag !== 8554) {
            break;
          }

          message.pruningPointUtxoSetOverrideNotification = PruningPointUtxoSetOverrideNotificationMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1071: {
          if (tag !== 8570) {
            break;
          }

          message.stopNotifyingPruningPointUtxoSetOverrideResponse =
            StopNotifyingPruningPointUtxoSetOverrideResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1073: {
          if (tag !== 8586) {
            break;
          }

          message.estimateNetworkHashesPerSecondResponse = EstimateNetworkHashesPerSecondResponseMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1075: {
          if (tag !== 8602) {
            break;
          }

          message.notifyVirtualDaaScoreChangedResponse = NotifyVirtualDaaScoreChangedResponseMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1076: {
          if (tag !== 8610) {
            break;
          }

          message.virtualDaaScoreChangedNotification = VirtualDaaScoreChangedNotificationMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1078: {
          if (tag !== 8626) {
            break;
          }

          message.getBalanceByAddressResponse = GetBalanceByAddressResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1080: {
          if (tag !== 8642) {
            break;
          }

          message.getBalancesByAddressesResponse = GetBalancesByAddressesResponseMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1082: {
          if (tag !== 8658) {
            break;
          }

          message.notifyNewBlockTemplateResponse = NotifyNewBlockTemplateResponseMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1083: {
          if (tag !== 8666) {
            break;
          }

          message.newBlockTemplateNotification = NewBlockTemplateNotificationMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1085: {
          if (tag !== 8682) {
            break;
          }

          message.getMempoolEntriesByAddressesResponse = GetMempoolEntriesByAddressesResponseMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1087: {
          if (tag !== 8698) {
            break;
          }

          message.getCoinSupplyResponse = GetCoinSupplyResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1089: {
          if (tag !== 8714) {
            break;
          }

          message.pingResponse = PingResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1091: {
          if (tag !== 8730) {
            break;
          }

          message.getMetricsResponse = GetMetricsResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1093: {
          if (tag !== 8746) {
            break;
          }

          message.getServerInfoResponse = GetServerInfoResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1095: {
          if (tag !== 8762) {
            break;
          }

          message.getSyncStatusResponse = GetSyncStatusResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1097: {
          if (tag !== 8778) {
            break;
          }

          message.getDaaScoreTimestampEstimateResponse = GetDaaScoreTimestampEstimateResponseMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1101: {
          if (tag !== 8810) {
            break;
          }

          message.submitTransactionReplacementResponse = SubmitTransactionReplacementResponseMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1103: {
          if (tag !== 8826) {
            break;
          }

          message.getConnectionsResponse = GetConnectionsResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1105: {
          if (tag !== 8842) {
            break;
          }

          message.getSystemInfoResponse = GetSystemInfoResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1107: {
          if (tag !== 8858) {
            break;
          }

          message.getFeeEstimateResponse = GetFeeEstimateResponseMessage.decode(reader, reader.uint32());
          continue;
        }
        case 1109: {
          if (tag !== 8874) {
            break;
          }

          message.getFeeEstimateExperimentalResponse = GetFeeEstimateExperimentalResponseMessage.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
        case 1111: {
          if (tag !== 8890) {
            break;
          }

          message.getCurrentBlockColorResponse = GetCurrentBlockColorResponseMessage.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<KaspadResponse>): KaspadResponse {
    return KaspadResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<KaspadResponse>): KaspadResponse {
    const message = createBaseKaspadResponse();
    message.id = object.id ?? 0;
    message.getCurrentNetworkResponse =
      object.getCurrentNetworkResponse !== undefined && object.getCurrentNetworkResponse !== null
        ? GetCurrentNetworkResponseMessage.fromPartial(object.getCurrentNetworkResponse)
        : undefined;
    message.submitBlockResponse =
      object.submitBlockResponse !== undefined && object.submitBlockResponse !== null
        ? SubmitBlockResponseMessage.fromPartial(object.submitBlockResponse)
        : undefined;
    message.getBlockTemplateResponse =
      object.getBlockTemplateResponse !== undefined && object.getBlockTemplateResponse !== null
        ? GetBlockTemplateResponseMessage.fromPartial(object.getBlockTemplateResponse)
        : undefined;
    message.notifyBlockAddedResponse =
      object.notifyBlockAddedResponse !== undefined && object.notifyBlockAddedResponse !== null
        ? NotifyBlockAddedResponseMessage.fromPartial(object.notifyBlockAddedResponse)
        : undefined;
    message.blockAddedNotification =
      object.blockAddedNotification !== undefined && object.blockAddedNotification !== null
        ? BlockAddedNotificationMessage.fromPartial(object.blockAddedNotification)
        : undefined;
    message.getPeerAddressesResponse =
      object.getPeerAddressesResponse !== undefined && object.getPeerAddressesResponse !== null
        ? GetPeerAddressesResponseMessage.fromPartial(object.getPeerAddressesResponse)
        : undefined;
    message.GetSinkResponse =
      object.GetSinkResponse !== undefined && object.GetSinkResponse !== null
        ? GetSinkResponseMessage.fromPartial(object.GetSinkResponse)
        : undefined;
    message.getMempoolEntryResponse =
      object.getMempoolEntryResponse !== undefined && object.getMempoolEntryResponse !== null
        ? GetMempoolEntryResponseMessage.fromPartial(object.getMempoolEntryResponse)
        : undefined;
    message.getConnectedPeerInfoResponse =
      object.getConnectedPeerInfoResponse !== undefined && object.getConnectedPeerInfoResponse !== null
        ? GetConnectedPeerInfoResponseMessage.fromPartial(object.getConnectedPeerInfoResponse)
        : undefined;
    message.addPeerResponse =
      object.addPeerResponse !== undefined && object.addPeerResponse !== null
        ? AddPeerResponseMessage.fromPartial(object.addPeerResponse)
        : undefined;
    message.submitTransactionResponse =
      object.submitTransactionResponse !== undefined && object.submitTransactionResponse !== null
        ? SubmitTransactionResponseMessage.fromPartial(object.submitTransactionResponse)
        : undefined;
    message.notifyVirtualChainChangedResponse =
      object.notifyVirtualChainChangedResponse !== undefined && object.notifyVirtualChainChangedResponse !== null
        ? NotifyVirtualChainChangedResponseMessage.fromPartial(object.notifyVirtualChainChangedResponse)
        : undefined;
    message.virtualChainChangedNotification =
      object.virtualChainChangedNotification !== undefined && object.virtualChainChangedNotification !== null
        ? VirtualChainChangedNotificationMessage.fromPartial(object.virtualChainChangedNotification)
        : undefined;
    message.getBlockResponse =
      object.getBlockResponse !== undefined && object.getBlockResponse !== null
        ? GetBlockResponseMessage.fromPartial(object.getBlockResponse)
        : undefined;
    message.getSubnetworkResponse =
      object.getSubnetworkResponse !== undefined && object.getSubnetworkResponse !== null
        ? GetSubnetworkResponseMessage.fromPartial(object.getSubnetworkResponse)
        : undefined;
    message.getVirtualChainFromBlockResponse =
      object.getVirtualChainFromBlockResponse !== undefined && object.getVirtualChainFromBlockResponse !== null
        ? GetVirtualChainFromBlockResponseMessage.fromPartial(object.getVirtualChainFromBlockResponse)
        : undefined;
    message.getBlocksResponse =
      object.getBlocksResponse !== undefined && object.getBlocksResponse !== null
        ? GetBlocksResponseMessage.fromPartial(object.getBlocksResponse)
        : undefined;
    message.getBlockCountResponse =
      object.getBlockCountResponse !== undefined && object.getBlockCountResponse !== null
        ? GetBlockCountResponseMessage.fromPartial(object.getBlockCountResponse)
        : undefined;
    message.getBlockDagInfoResponse =
      object.getBlockDagInfoResponse !== undefined && object.getBlockDagInfoResponse !== null
        ? GetBlockDagInfoResponseMessage.fromPartial(object.getBlockDagInfoResponse)
        : undefined;
    message.resolveFinalityConflictResponse =
      object.resolveFinalityConflictResponse !== undefined && object.resolveFinalityConflictResponse !== null
        ? ResolveFinalityConflictResponseMessage.fromPartial(object.resolveFinalityConflictResponse)
        : undefined;
    message.notifyFinalityConflictResponse =
      object.notifyFinalityConflictResponse !== undefined && object.notifyFinalityConflictResponse !== null
        ? NotifyFinalityConflictResponseMessage.fromPartial(object.notifyFinalityConflictResponse)
        : undefined;
    message.finalityConflictNotification =
      object.finalityConflictNotification !== undefined && object.finalityConflictNotification !== null
        ? FinalityConflictNotificationMessage.fromPartial(object.finalityConflictNotification)
        : undefined;
    message.finalityConflictResolvedNotification =
      object.finalityConflictResolvedNotification !== undefined && object.finalityConflictResolvedNotification !== null
        ? FinalityConflictResolvedNotificationMessage.fromPartial(object.finalityConflictResolvedNotification)
        : undefined;
    message.getMempoolEntriesResponse =
      object.getMempoolEntriesResponse !== undefined && object.getMempoolEntriesResponse !== null
        ? GetMempoolEntriesResponseMessage.fromPartial(object.getMempoolEntriesResponse)
        : undefined;
    message.shutdownResponse =
      object.shutdownResponse !== undefined && object.shutdownResponse !== null
        ? ShutdownResponseMessage.fromPartial(object.shutdownResponse)
        : undefined;
    message.getHeadersResponse =
      object.getHeadersResponse !== undefined && object.getHeadersResponse !== null
        ? GetHeadersResponseMessage.fromPartial(object.getHeadersResponse)
        : undefined;
    message.notifyUtxosChangedResponse =
      object.notifyUtxosChangedResponse !== undefined && object.notifyUtxosChangedResponse !== null
        ? NotifyUtxosChangedResponseMessage.fromPartial(object.notifyUtxosChangedResponse)
        : undefined;
    message.utxosChangedNotification =
      object.utxosChangedNotification !== undefined && object.utxosChangedNotification !== null
        ? UtxosChangedNotificationMessage.fromPartial(object.utxosChangedNotification)
        : undefined;
    message.getUtxosByAddressesResponse =
      object.getUtxosByAddressesResponse !== undefined && object.getUtxosByAddressesResponse !== null
        ? GetUtxosByAddressesResponseMessage.fromPartial(object.getUtxosByAddressesResponse)
        : undefined;
    message.getSinkBlueScoreResponse =
      object.getSinkBlueScoreResponse !== undefined && object.getSinkBlueScoreResponse !== null
        ? GetSinkBlueScoreResponseMessage.fromPartial(object.getSinkBlueScoreResponse)
        : undefined;
    message.notifySinkBlueScoreChangedResponse =
      object.notifySinkBlueScoreChangedResponse !== undefined && object.notifySinkBlueScoreChangedResponse !== null
        ? NotifySinkBlueScoreChangedResponseMessage.fromPartial(object.notifySinkBlueScoreChangedResponse)
        : undefined;
    message.sinkBlueScoreChangedNotification =
      object.sinkBlueScoreChangedNotification !== undefined && object.sinkBlueScoreChangedNotification !== null
        ? SinkBlueScoreChangedNotificationMessage.fromPartial(object.sinkBlueScoreChangedNotification)
        : undefined;
    message.banResponse =
      object.banResponse !== undefined && object.banResponse !== null
        ? BanResponseMessage.fromPartial(object.banResponse)
        : undefined;
    message.unbanResponse =
      object.unbanResponse !== undefined && object.unbanResponse !== null
        ? UnbanResponseMessage.fromPartial(object.unbanResponse)
        : undefined;
    message.getInfoResponse =
      object.getInfoResponse !== undefined && object.getInfoResponse !== null
        ? GetInfoResponseMessage.fromPartial(object.getInfoResponse)
        : undefined;
    message.stopNotifyingUtxosChangedResponse =
      object.stopNotifyingUtxosChangedResponse !== undefined && object.stopNotifyingUtxosChangedResponse !== null
        ? StopNotifyingUtxosChangedResponseMessage.fromPartial(object.stopNotifyingUtxosChangedResponse)
        : undefined;
    message.notifyPruningPointUtxoSetOverrideResponse =
      object.notifyPruningPointUtxoSetOverrideResponse !== undefined &&
      object.notifyPruningPointUtxoSetOverrideResponse !== null
        ? NotifyPruningPointUtxoSetOverrideResponseMessage.fromPartial(object.notifyPruningPointUtxoSetOverrideResponse)
        : undefined;
    message.pruningPointUtxoSetOverrideNotification =
      object.pruningPointUtxoSetOverrideNotification !== undefined &&
      object.pruningPointUtxoSetOverrideNotification !== null
        ? PruningPointUtxoSetOverrideNotificationMessage.fromPartial(object.pruningPointUtxoSetOverrideNotification)
        : undefined;
    message.stopNotifyingPruningPointUtxoSetOverrideResponse =
      object.stopNotifyingPruningPointUtxoSetOverrideResponse !== undefined &&
      object.stopNotifyingPruningPointUtxoSetOverrideResponse !== null
        ? StopNotifyingPruningPointUtxoSetOverrideResponseMessage.fromPartial(
            object.stopNotifyingPruningPointUtxoSetOverrideResponse
          )
        : undefined;
    message.estimateNetworkHashesPerSecondResponse =
      object.estimateNetworkHashesPerSecondResponse !== undefined &&
      object.estimateNetworkHashesPerSecondResponse !== null
        ? EstimateNetworkHashesPerSecondResponseMessage.fromPartial(object.estimateNetworkHashesPerSecondResponse)
        : undefined;
    message.notifyVirtualDaaScoreChangedResponse =
      object.notifyVirtualDaaScoreChangedResponse !== undefined && object.notifyVirtualDaaScoreChangedResponse !== null
        ? NotifyVirtualDaaScoreChangedResponseMessage.fromPartial(object.notifyVirtualDaaScoreChangedResponse)
        : undefined;
    message.virtualDaaScoreChangedNotification =
      object.virtualDaaScoreChangedNotification !== undefined && object.virtualDaaScoreChangedNotification !== null
        ? VirtualDaaScoreChangedNotificationMessage.fromPartial(object.virtualDaaScoreChangedNotification)
        : undefined;
    message.getBalanceByAddressResponse =
      object.getBalanceByAddressResponse !== undefined && object.getBalanceByAddressResponse !== null
        ? GetBalanceByAddressResponseMessage.fromPartial(object.getBalanceByAddressResponse)
        : undefined;
    message.getBalancesByAddressesResponse =
      object.getBalancesByAddressesResponse !== undefined && object.getBalancesByAddressesResponse !== null
        ? GetBalancesByAddressesResponseMessage.fromPartial(object.getBalancesByAddressesResponse)
        : undefined;
    message.notifyNewBlockTemplateResponse =
      object.notifyNewBlockTemplateResponse !== undefined && object.notifyNewBlockTemplateResponse !== null
        ? NotifyNewBlockTemplateResponseMessage.fromPartial(object.notifyNewBlockTemplateResponse)
        : undefined;
    message.newBlockTemplateNotification =
      object.newBlockTemplateNotification !== undefined && object.newBlockTemplateNotification !== null
        ? NewBlockTemplateNotificationMessage.fromPartial(object.newBlockTemplateNotification)
        : undefined;
    message.getMempoolEntriesByAddressesResponse =
      object.getMempoolEntriesByAddressesResponse !== undefined && object.getMempoolEntriesByAddressesResponse !== null
        ? GetMempoolEntriesByAddressesResponseMessage.fromPartial(object.getMempoolEntriesByAddressesResponse)
        : undefined;
    message.getCoinSupplyResponse =
      object.getCoinSupplyResponse !== undefined && object.getCoinSupplyResponse !== null
        ? GetCoinSupplyResponseMessage.fromPartial(object.getCoinSupplyResponse)
        : undefined;
    message.pingResponse =
      object.pingResponse !== undefined && object.pingResponse !== null
        ? PingResponseMessage.fromPartial(object.pingResponse)
        : undefined;
    message.getMetricsResponse =
      object.getMetricsResponse !== undefined && object.getMetricsResponse !== null
        ? GetMetricsResponseMessage.fromPartial(object.getMetricsResponse)
        : undefined;
    message.getServerInfoResponse =
      object.getServerInfoResponse !== undefined && object.getServerInfoResponse !== null
        ? GetServerInfoResponseMessage.fromPartial(object.getServerInfoResponse)
        : undefined;
    message.getSyncStatusResponse =
      object.getSyncStatusResponse !== undefined && object.getSyncStatusResponse !== null
        ? GetSyncStatusResponseMessage.fromPartial(object.getSyncStatusResponse)
        : undefined;
    message.getDaaScoreTimestampEstimateResponse =
      object.getDaaScoreTimestampEstimateResponse !== undefined && object.getDaaScoreTimestampEstimateResponse !== null
        ? GetDaaScoreTimestampEstimateResponseMessage.fromPartial(object.getDaaScoreTimestampEstimateResponse)
        : undefined;
    message.submitTransactionReplacementResponse =
      object.submitTransactionReplacementResponse !== undefined && object.submitTransactionReplacementResponse !== null
        ? SubmitTransactionReplacementResponseMessage.fromPartial(object.submitTransactionReplacementResponse)
        : undefined;
    message.getConnectionsResponse =
      object.getConnectionsResponse !== undefined && object.getConnectionsResponse !== null
        ? GetConnectionsResponseMessage.fromPartial(object.getConnectionsResponse)
        : undefined;
    message.getSystemInfoResponse =
      object.getSystemInfoResponse !== undefined && object.getSystemInfoResponse !== null
        ? GetSystemInfoResponseMessage.fromPartial(object.getSystemInfoResponse)
        : undefined;
    message.getFeeEstimateResponse =
      object.getFeeEstimateResponse !== undefined && object.getFeeEstimateResponse !== null
        ? GetFeeEstimateResponseMessage.fromPartial(object.getFeeEstimateResponse)
        : undefined;
    message.getFeeEstimateExperimentalResponse =
      object.getFeeEstimateExperimentalResponse !== undefined && object.getFeeEstimateExperimentalResponse !== null
        ? GetFeeEstimateExperimentalResponseMessage.fromPartial(object.getFeeEstimateExperimentalResponse)
        : undefined;
    message.getCurrentBlockColorResponse =
      object.getCurrentBlockColorResponse !== undefined && object.getCurrentBlockColorResponse !== null
        ? GetCurrentBlockColorResponseMessage.fromPartial(object.getCurrentBlockColorResponse)
        : undefined;
    return message;
  }
};

export type RPCDefinition = typeof RPCDefinition;
export const RPCDefinition = {
  name: 'RPC',
  fullName: 'protowire.RPC',
  methods: {
    messageStream: {
      name: 'MessageStream',
      requestType: KaspadRequest,
      requestStream: true,
      responseType: KaspadResponse,
      responseStream: true,
      options: {}
    }
  }
} as const;

export interface RPCServiceImplementation<CallContextExt = {}> {
  messageStream(
    request: AsyncIterable<KaspadRequest>,
    context: CallContext & CallContextExt
  ): ServerStreamingMethodResult<DeepPartial<KaspadResponse>>;
}

export interface RPCClient<CallOptionsExt = {}> {
  messageStream(
    request: AsyncIterable<DeepPartial<KaspadRequest>>,
    options?: CallOptions & CallOptionsExt
  ): AsyncIterable<KaspadResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER');
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER');
  }
  return num;
}

export type ServerStreamingMethodResult<Response> = { [Symbol.asyncIterator](): AsyncIterator<Response, void> };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
